################################################################################
# Copyright (c) IBM Corporation 2020
################################################################################

################################################################################
# Configure dependency installations
################################################################################
# 
#ansible_python_interpreter: /_PRDS/PYTHON/SCYPH38/pyz/bin/python3
#PYZ: "/_PRDS/PYTHON/SCYPH38/pyz"
#ZOAU: "/_PRDS/ZOAUTIL/SBGYZFS"

ansible_python_interpreter: /_PRDS/PYT/current/pyz/bin/python3
PYZM: "/_PRDS/PYT"
PYZ: "{{ PYZM }}/current/pyz"
ZOAM: "/_PRDS/ZOA"
ZOAU: "{{ ZOAM }}/current"

################################################################################
# Playbook enviroment variables
################################################################################
environment_vars:
  ZOAU_HOME: "{{ ZOAU }}"
  CLASSPATH: "{{ ZOAU }}/lib/*"
  JAVA_HOME: "/usr/lpp/java/J8.0_64"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib"
  MANPATH: "{{ ZOAU }}/docs/%L"
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin"
  PYTHONPATH: "{{ ZOAM }}/zoautil_py_current"
  ANSIBLE_REMOTE_TMP: /tmp/ansible
  LANG: "C"
  _BPXK_AUTOCVT: "ON"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  _ENCODE_FILE_NEW: "IBM-1047"
  _ENCODE_FILE_EXISTING: "IBM-1047"
